# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://tiliatranslations.it
title: Angela Brisotto, MA | Language Services
email: angela@tiliatranslations.it
author: Angela Brisotto
description: Iâ€™m Angela Brisotto and I build bridges that connect English and Polish with Italian. Combining analysis, accuracy and wordsmithery, I translate texts, localise websites, revise translations, proofread texts, and transcribe audio and video materials. Welcome to my website!

copyright: |
  TILIA TRANSLATIONS DI ANGELA BRISOTTO
  <br>
  VAT: 05247030264
  <br>
  31027, Spresiano (TV)
  <br>
  Italy
  <br>
  <br>
  Copyright &copy; 2022 Tilia Translations di Angela Brisotto. All Rights Reserved.
  Credits: Theme by <a href="https://startbootstrap.com/">Start Bootstrap</a>.
  <br>
  <br>

credits: |
  A NOTE ON EMAILS
  <br>
  <br>
  It would be very helpful if you could be as specific as possible when writing your request. I usually answer business-related emails in the morning (CET) from Monday to Thursday. Thank you for your patience. 
  <br>
  I wish you a great day ahead.
  <br>
  <br>
  OFFICE HOURS 
  <br>
  <br>
  Monday to Thursday, - 9 AM to 4 PM (CET)
  <br>
  <br>
  Address: <a href="mailto:angela@tiliatranslations.it">angela@tiliatranslations.it</a>
  <br>
  Addressee: Angela Brisotto (she/her)


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/angela-brisotto
  - title: instagram
    url: https://www.instagram.com/tiliatranslationsangela/
